name: Deployment exersice 2
on: push
env:
  REACT_APP_BACKEND: https://abc.xyz.com
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: get-code
        uses: actions/checkout@v3
      - name: Cache dependencies
        uses: actions/cache@v4
        with:
          path: ~/.npm
          key: deps-node-modules-${{ hashFiles('**/package-lock.json') }}
      - name: Install dependencies
        run: npm install
      - name: Lint code
        run: echo "linting the code"
  test:
    needs: lint
    runs-on: ubuntu-latest
    steps:
      - name: get-code
        uses: actions/checkout@v3
      - name: Install dependencies
        run: npm install
      - name: Test code
        run: echo "testing the code"
  build:
    needs: test
    runs-on: ubuntu-latest
    outputs:
      script-file: ${{steps.publish.outputs.script-file}}
    steps:
      - name: get-code
        uses: actions/checkout@v3
      - name: Install dependencies
        run: npm install
      - name: Build code
        run: npm run build
      - name: Publish Js file name
        id: publish
        run: find build/*.html -type f -execdir echo 'script-file={}' >>$GITHUB_OUTPUT ';'
      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: dist-files
          path: build
  deploy:
    env:
      PORT: 3000
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: get-code
        uses: actions/download-artifact@v4
        with:
          name: dist-files
      - name: Output content
        run: ls
      - name: Output filename
        run: echo "${{needs.build.outputs.script-file}}"
      - name: read environment variable
        run: echo $PORT
      - name: read react app backend variable
        run: echo ${{ secrets.REACT_APP_BACKEND }}
      - name: Deploy code
        run: echo "deploying the code"
